apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: playground-app
  name: playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playground-app
  strategy: {}
  template:
    metadata:
      labels:
        app: playground-app
    spec:
      containers:
      - image: to_be_replaced
        name: app-container
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: playground-svc
  name: playground-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: playground-app
  type: NodePort